---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.123.111"}]
  customize:
    cpus: 2
    memory: 3072
  linked_clone: true

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8

suites:
  - name: karaf
    driver:
      network:
        - ["private_network", {ip: "192.168.123.222"}]
      customize:
        memory: 2048
    run_list:
      - recipe[aet::karaf]
      - recipe[aet::deploy_aet_for_karaf]
      - recipe[aet::postdeploy_restart]
      - recipe[aet::reboot]
    attributes:
      java:
        jdk_version: '8'
    verifier:
      inspec_tests:
        - test/karaf
  - name: activemq
    driver:
      network:
        - ["private_network", {ip: "192.168.123.223"}]
      customize:
        memory: 1024
    run_list:
      - recipe[aet::activemq]
    attributes:
      java:
        jdk_version: '8'
    verifier:
      inspec_tests:
        - test/activemq
  - name: seleniumgrid
    driver:
      network:
        - ["private_network", {ip: "192.168.123.224"}]
      customize:
        memory: 768
    run_list:
      - recipe[java::default]
      - recipe[aet::seleniumgrid_hub]
    attributes:
      java:
        jdk_version: '8'
    verifier:
      inspec_tests:
        - test/seleniumgrid
  - name: apache2
    driver:
      network:
        - ["private_network", {ip: "192.168.123.225"}]
      customize:
        memory: 1024
    run_list:
      - recipe[aet::apache]
    verifier:
      inspec_tests:
        - test/apache2
  - name: browsermob
    driver:
      network:
        - ["private_network", {ip: "192.168.123.226"}]
      customize:
        memory: 768
    run_list:
      - recipe[aet::browsermob]
    attributes:
      java:
        jdk_version: '8'
    verifier:
      inspec_tests:
        - test/browsermob
  - name: mongo
    driver:
      network:
        - ["private_network", {ip: "192.168.123.227"}]
      customize:
        memory: 1024
    run_list:
      - recipe[aet::mongo]
    attributes:
      mongodb:
        package_version: '3.2.3'
    verifier:
      inspec_tests:
        - test/mongo
